### ISSUE TITLE
Nested view with Neovim

### ISSUE THREAD

**Issue by pr4th4m** [ptzz/lf.vim#1]
I guess `lf` is opening up in seperate process every time, take a look at the pic below
<img width="1242" alt="Screen Shot 2019-06-20 at 11 15 38 am" src="https://user-images.githubusercontent.com/925565/59811425-43c10980-934d-11e9-8fc1-1aec26c4ae66.png">

**Comment by ptzz** [comment]
Wow, a user, welcome! 😄 I haven't seen this and using neovim myself. Do you have the same issue with [ranger.vim](https://github.com/francoiscabrol/ranger.vim)? `lf.vim` is a fork of that basically just replacing the `ranger` executable with `lf`.

**Comment by pr4th4m** [comment]
Nope, ranger works perfectly fine with neovim.
Version details
```
tmux 2.9a
NVIM v0.3.7
lf r12
ranger 1.9.2
```

**Comment by ptzz** [comment]
Got it. Probably not something I'll have time to look into but a PR would be most welsome!

**Comment by ptzz** [comment]
I have this in my .vimrc, otherwise I get a `[Process exited 0]` and have to press Enter when exiting `lf`:

```
augroup terminal
    autocmd!
    " Close buffer immediately on exit
    autocmd TermClose * bd!
augroup end
```

Does that fix your issue too? If yes that could be a hint for a more proper fix.

**UPDATE**: Just tested with ranger plugin, and it's the same behaviour wrt. `[Process exited 0]`, so probably won't fix your issue.

**Comment by ptzz** [comment]
Which command do you use to launch Lf and which terminal and OS? I don’t use tmux, tried without it? Could you send small .vimrc and steps to repro?

**Comment by pr4th4m** [comment]
This is the exact issue I am facing https://github.com/gokcehan/lf/issues/176

OS: MacOS
Terminal: Kitty
LF launch command: `map - :Lf<CR>`
Facing same issue without tux as well :(

Not sure if this issue belong here, I am closing the ticket for now.
Thanks mate :)

**Comment by ptzz** [comment]
I wasn’t aware of the lf.vim script in that repo. Have you tried both and same result?

**Comment by pr4th4m** [comment]
I did try `lf.vim` but unfortunately it does not work with neovim, also, It's not the same error.

**Comment by ptzz** [comment]
Does the error (screenshot) happen when opening Lf or when opening a file after Lf has been opened?

**Comment by pr4th4m** [comment]
When opening a file after Lf is opened

**Comment by ptzz** [comment]
I could repro and fixed an issue, please try the latest version. And make sure to use the `open` command from within `lf` (i.e. not `e`).

**Comment by pr4th4m** [comment]
Thanks mate, that fixed it 😄 
There's another issue with status line (lightline.vim), will raise a seperate ticket for better tracking.
