### ISSUE TITLE
Unable to find the project in vim Awesome

### ISSUE THREAD

**Issue by fabriceHategekimana** [ptzz/lf.vim#11]
Personnally, I think this project is great. I am a vim and lf user for my daily work so this plugin was a real life saver.

It's a shame that this project can't be found in Vim Awesome. 
I don't know if you know about this site, but it's like a store for vim plugins were everyone can look for plugins to install.

The link is [here](https://vimawesome.com/)

Of course, there is no need to add your project here. I just think it could be cool if more people know about your work.

Kind regards

**Comment by ptzz** [comment]
Glad that you’re happy with the plugin! Feel free to spread the word 🙂
