### ISSUE TITLE
Overriding the `open` command has no effect

### ISSUE THREAD

**Issue by mroavi** [ptzz/lf.vim#12]
I added this code to my `lfrc` in order to open text files with nvim and other files, like images, with xdg-open.
```
# Open with $EDITOR or xdg-open based on type of file
cmd open ${{
    case $(file --mime-type "$f" -bL) in
        text/*|application/json) $EDITOR "$f";;
        *) xdg-open "$f" ;;
    esac
}}
```
This works fine if I open `lf` from the terminal. However, it does not work with `lf`'s vim plugin.

**Comment by ptzz** [comment]
I think this is expected behavior. The plugin hijacks the `open` command, i.e. the lf `open` action will always open the file in the originating vim session when lf was started using the plugin

**Comment by mroavi** [comment]
Understood. On the other hand, this would be an amazing feature. Not having to leave vim/nvim to open a pdf, image, video etc. would be a killer feature. Would you be interested in this?

**Comment by ptzz** [comment]
I actually don’t use this plugin anymore since fzf.vim fits my workflows better.

Anyway I think what you’re asking for would require changes in lf itself. Or perhaps you could define a custom new open command in .lfrc and use that instead when inside vim.

**Comment by mroavi** [comment]
The latter idea worked. Thanks a lot.
