### ISSUE TITLE
Disable line numbers when lf is launched

### ISSUE THREAD

**Issue by mroavi** [ptzz/lf.vim#13]
Could you disable the line numbers in the buffer that gets created when lf is launched? They are not adding anything and hence are distracting. It is also confusing that the one at the bottom of the buffer gets highlighted.

**Comment by ptzz** [comment]
Not using this plugin myself anymore, PRs welcome.

**Comment by mroavi** [comment]
PR opened: https://github.com/ptzz/lf.vim/pull/15
