### ISSUE TITLE
Wrong buffer displayed when lf is closed

### ISSUE THREAD

**Issue by mroavi** [ptzz/lf.vim#14]
I just noticed a strange bug after using lf for some time. Here is how to reproduce it:

Open nvim with several files as arguments:
```zsh
nvim a.txt b.txt c.txt
```
The file `a.txt` will be displayed on start. Open and quit the lf plugin. File `c.txt` gets displayed. I think that the correct behavior is to display the buffer from which you launched lf.

**Comment by mroavi** [comment]
The problem is inside `bclose.vim`, specifically in the `if` statement in line 50:
```vim
    if prevbuf > 0 && buflisted(prevbuf) && prevbuf != w
      buffer #
    else
      bprevious
    endif
```
The last condition, `prevbuf != w` evaluates to false, and hence `bprevious` is executed.

**Comment by mroavi** [comment]
I opened an issue in `bclose.vim`: https://github.com/rbgrouleff/bclose.vim/issues/8

**Comment by ptzz** [comment]
Perhaps https://github.com/moll/vim-bbye solves the problem and should replace bclose? It looks more maintained.

**Comment by mroavi** [comment]
I came up with a fix that gets rid of dependencies. Can you test https://github.com/ptzz/lf.vim/pull/17?
