### ISSUE TITLE
Status line disappears after opening file from lf

### ISSUE THREAD

**Issue by pr4th4m** [ptzz/lf.vim#2]
I am using https://github.com/itchyny/lightline.vim as my neovim status line, after opening a file from `lf` status line disappears.

Have attached two snaps
1. Lightline with ranger 
<img width="1273" alt="ranger" src="https://user-images.githubusercontent.com/925565/59998337-79922500-96a2-11e9-8e3e-24ee1753b939.png">

2. Lightline with lf 
<img width="1273" alt="lf" src="https://user-images.githubusercontent.com/925565/59998338-79922500-96a2-11e9-93d2-710c7c1010dd.png">

I am guessing it's a redraw issue

**Comment by ptzz** [comment]
Please try now (the issue was hidden to me since I had autocommands in my .vimrc that removed and restored statusline on entering/exiting terminal sessions).

**Comment by pr4th4m** [comment]
Thanks for fixing the bug mate, cheers 🍻
