### ISSUE TITLE
lf_replace_netrw not working with vim-floaterm 

### ISSUE THREAD

**Issue by BachoSeven** [ptzz/lf.vim#20]
Using `let g:lf_replace_netrw = 1` is not working after the switch to floating windows: `nvim DIRECTORY` opens an an empty buffer where the directory is open and visible in a floating terminal, but the focus is on the buffer.

**Comment by BachoSeven** [comment]
The empty buffer is also in insert mode, which is odd.

**Comment by ptzz** [comment]
Could you please have a look @sitiom?

**Comment by sitiom** [comment]
Huh, seems like a floaterm bug to me. Normally, it should be focused on the floating window. 

Related line:
https://github.com/ptzz/lf.vim/blob/9d333aaea4967e3e738c77a8f6ffe466beb2bcee/plugin/lf.vim#L109

> `nvim DIRECTORY` opens an an empty buffer where the directory is open and visible in a floating terminal, but the focus is on the buffer.

`:e DIRECTORY` works fine though.

So far I have only tested this in neovim, does this happen in vim?

**Comment by sitiom** [comment]
Opened an issue: https://github.com/voldikss/vim-floaterm/issues/252

**Comment by voldikss** [comment]
Use `timer_start` solves the problem.

```vim
autocmd BufEnter * let s:buf_path = expand("%") | if isdirectory(s:buf_path) | bdelete! | call timer_start(100, {->execute('FloatermNew lf')}) | endif
```
