### ISSUE TITLE
Removal of "g:floaterm_open_command" in vim-floaterm broke wrapper

### ISSUE THREAD

**Issue by BachoSeven** [ptzz/lf.vim#23]
See this [PR](https://github.com/voldikss/vim-floaterm/pull/248) which was just merged; it looks like `g:floaterm_open_command` was replaced with `g:floaterm_opener`, and it works somewhat differently. I tried removing the `g:floaterm_open_command` argument from [this](https://github.com/ptzz/lf.vim/blob/master/plugin/lf.vim#L71) line altogether, as seen on the [upstream](https://github.com/voldikss/vim-floaterm/commit/b838dd126c4fc0a595590d495c35a1f75483aa3d#diff-885adf106acf982c29a6d9dd28dac0f3c2234d1d14116d3703b45544c7807ad9L38) wrapper, but it did not work. Documentation for `g:floaterm_opener` should be [here](https://github.com/voldikss/vim-floaterm#gfloaterm_opener).

The error I get is:
``` vim
Error detected while processing function <SNR>97_on_floaterm_close[26]..LfCallback[21]..floaterm#util#open:
line    2:
E730: using List as a String
```

**Comment by ptzz** [comment]
What is the problem exactly? I just updated and run lf.vim revision 3223bcc and  vim-floatterm b838dd1 and `:Lf` seems to work.
