### ISSUE TITLE
How to not use floatterm

### ISSUE THREAD

**Issue by zdcthomas** [ptzz/lf.vim#28]
Hello, I recently updated to the most recent version of this plugin, and I keep getting the `"Failed to open a floating terminal. Make sure `voldikss/vim-floaterm` is installed."` error when trying to open using `:Lf`
Is there no way of using this plugin now without using Floatterm?

I'm also in Neovim so there's no need for the floatterm plugin as that's builtin to nvim 

Thanks!

**Comment by ptzz** [comment]
That’s correct. I didn’t see any downside of it vs the previous approach which was a bit inconsistent between vim and neovim. I guess you could use a previous revision if you prefer.

**Comment by zdcthomas** [comment]
Ok cool, my workflow always just centered around having lf appear in the window, but I guess that's not supported. Thanks for your hard work on this btw!

**Comment by ptzz** [comment]
I think that can approximately be achieved by configuring the window size.

I rarely use lf myself, fzf fits my workflow better. However I accepted the floaterm PR since I preferred its behavior for split windows and got rid of the need to distinguish between vim and neovim.

**Comment by zdcthomas** [comment]
No worries, thanks!
