### ISSUE TITLE
How to open file using lf in vertical split by default? 

### ISSUE THREAD

**Issue by homie-desktop** [ptzz/lf.vim#29]
I can't seem to find the option or documentation to enable opening files using LF in vertical split by default, is there any way to do that, instead of defaulting to horizontal split when opening files? Thanks

**Comment by ptzz** [comment]
I don't think there is an option to open in a split at all. Do you have some configuration to have files open in a horizontal split? For me, files just open in the current window.

**Comment by homie-desktop** [comment]
> I don't think there is an option to open in a split at all. Do you have some configuration to have files open in a horizontal split? For me, files just open in the current window.

Hi, I managed to open files in vertical split by configuring the floaterm plugin, by default floaterm open files horizontally when load first before LF. But if LF loads first then it opens file in the current window. I used floaterm option of `let g:floaterm_opener = 'vsplit'` then it now opens file vertically as I wanted. Thanks!
