### ISSUE TITLE
[Process exited 0] on 'q' exit while browsing

### ISSUE THREAD

**Issue by ghyatzo** [ptzz/lf.vim#3]
Hello,

If i start the lf plug in, when i try to exit the file explorer i don't immediately get back where i started but i get a blank page first with the text
`[Process exited 0]`
and on the status line
`term://.//31215:lf -selection-path=/tmp/chosenfile "some/path"`

I then have to press q again to properly exit.

**Comment by ptzz** [comment]
Did you add the `rbgrouleff/bclose.vim` plugin as described in the `README`?

**Comment by ghyatzo** [comment]
I thought i did but i spelled the repo wrongly and missed the PlugInstall error.
Now it works, sorry for opening a useless issue.

**Comment by ptzz** [comment]
@ghyatzo No worries, not exactly obvious what the error is.. I'll see if I can make it "fail better". So far this plugin mostly a copy of `ranger.vim`.
