### ISSUE TITLE
Allow setting a path in Lfcd

### ISSUE THREAD

**Issue by Dimfred** [ptzz/lf.vim#30]
Hi I would like to specify a folder when I activate `Lfcd` like in `:Lfcd my/custom/path`.

Lf normally gets opened in the current directory, I have a special commands where I only look for projects, and all my projects are in a workspace dir, which I would like here to popup. 
Sadly the custom `-command` options doesn't help here in overwriting the directory.

I looked through it but very much suck in vim script, if you could add that I would really appreciate it :)

**Comment by Eyjafjallajokull** [comment]
You can use plugin function directly: `:call OpenLfIn("my/custom/path", "cd")`

https://github.com/ptzz/lf.vim/blob/master/plugin/lf.vim#L75

**Comment by Dimfred** [comment]
Ahh thx. Have missed that.
