### ISSUE TITLE
dynamic values for Width and Height

### ISSUE THREAD

**Issue by rodhash** [ptzz/lf.vim#32]
Hi,

Is there a way to set dynamic values for width / height?

ie: If I opens up the terminal in full screen or in smaller size, it'd have the proper values set according to the terminal size.

I tried different things for `g:lf_width` / `g:lf_height` variables without success, and if I just leave the default values, the ones from LF itself, it doesn't seem to work properly for me.

I ended up doing a small hack in those floaterm values, here:

https://github.com/ptzz/lf.vim/blob/eab8f04b2953f08e3fcd425585598d176369ae4b/plugin/lf.vim#L36

But I was wondering if we can accomplish this without messing with the plugin files. Maybe those two variables could have dynamic values?

Let me show you what I mean:

1. In the 1st try the width is messed up after resizing the terminal
2. In the 2nd try it works but I had to hack the mentioned file.

https://user-images.githubusercontent.com/29671981/162652647-5e3a4d9e-36eb-4592-b005-2e86e628a76c.mp4

Thanks.

**Comment by ptzz** [comment]
Hi, I can't replicate the issue. I have no customized width/height settings and the floaterm window is scaled according to terminal width height. I'm on Mac + iTerm + neovim though, maybe that makes a difference. Does it work as expected for you for any other floaterm window (i.e. is the issue with lf.vim or floaterm)?

**Comment by rodhash** [comment]
I'm not sure but it seems to me that those variables (width / height) are staticly set to value X, the values when the terminal is opened. So if I resize the terminal window it doesn't show the floaterm properly since the terminal now has different width/height.

I'm using Linux (KDE) and Neovim 0.7, tried two terminals: kitty and alacritty, but both have the same behaviour. I have the impression those two variables needed some tweaking.

I'll dig a bit more on this issue but that's alright, that hack/workaround is helping me already.

**Comment by seantwie03** [comment]
I was also unable to replicate this issue on Windows. Tested using default settings for floatterm and lf.vim on pwsh.exe in Windows Terminal, and nvim-qt.exe.

**Comment by rodhash** [comment]
Well I'm unsure what's happening but thanks for checking, in this case it should be some bug local to my config, right now I'm dual booting into another Linux OS and now even running another DE (Gnome), and it still happens.

So I guess I'll keep running with this little hack in place because sometimes the LF "locked" to a fixed width and height can be very annoying depending on which position/size my terminal is.

Thanks again
