### ISSUE TITLE
:Lf not opening window properly

### ISSUE THREAD

**Issue by mrchoc** [ptzz/lf.vim#33]
Floaterm window closes immediately after running :Lf

I have lf.vim loading before vim-floaterm in init.vim, so I'm not sure what's going on.

https://user-images.githubusercontent.com/65016628/174515787-d758ac4b-64d1-43bd-a14c-668af36dbeb7.mov

**Comment by Spencerduran** [comment]
Having the same issue, disappears instantly

**Comment by sergiza** [comment]
Same issue, any news?

**Comment by sergiza** [comment]
I had this issue. For me it was because my lf is an appimage. 
Just open lf.vim and change
`
  let s:lf_command = 'lf'
`
to
`
  let s:lf_command = '/path/of/your/lf/appimage'
`

**Comment by ptzz** [comment]
Is appimage the issue for all of you guys? If not, is `lf` in PATH and can be executed from within vim? Using `g:lf_command_override` might be more convenient than hacking lf.vim for the first case.

**Comment by ptzz** [comment]
I added an error printout in 9deb014ae3b0c10e4b8e6fa6efaf4ea4811a9002 so at least it's not completely silent when lf binary cannot be found.

**Comment by ptzz** [comment]
FYI the latest version e77c40a5ff3e900fb2c348939c636667df647bc8 fixes a potentially related issue with `g:lf_command_override`.
