### ISSUE TITLE
Error detected while processing function <SNR>109_on_floaterm_close[27]..LfCallback:           

### ISSUE THREAD

**Issue by andrewpedia** [ptzz/lf.vim#37]
Error detected while processing function <SNR>109_on_floaterm_close[27]..LfCallback:           
line   26:
lf returned non-zero exit code 127

**Comment by ptzz** [comment]
Looks like the `lf` binary can’t be found.

**Comment by boikyeet** [comment]
Had the same issue.
Justo do a `whereis lf` and move it from wherever it is to /usr/local/bin
