### ISSUE TITLE
<Esc> tries to open current file and causes undefined behavior

### ISSUE THREAD

**Issue by Xemptuous** [ptzz/lf.vim#38]
When opening a new window with `<leader> f` it seems that lf's default keybindings cause issues.

When pressing `<Esc>` with the lf floaterm window open, it tries to open the file in the buffer that I had open when initializing the window. Further keypresses of `<Esc>` cause the file to enter `-- INSERT --` mode, and inserts newlines of `exit`, and if i long-press `<Esc>`, random text will be inserted in newlines depending on how long the key is held.

![image](https://user-images.githubusercontent.com/99044751/200997713-803dcdfe-491b-432e-bbcb-eb2b6f056625.png)

I can't exit the insert mode either, unless I use my custom keybind for `<Esc>`. Upon exiting, it enters a read-only view of lf of the file, allowing the normal `q` keybind to be used to go back to original lf view.

**Comment by ptzz** [comment]
When I press ESC in lf floaterm window I get `unknown mapping: <esc>` at the bottom of the window. Same in `lf` running outside of vim. Do you have ESC mapped in `.lfrc`?
