### ISSUE TITLE
Not changing directory at the first try

### ISSUE THREAD

**Issue by Archie-2021** [ptzz/lf.vim#39]
When I run `:Lf` it is going to go to the location for the previous buffer in the first try, I have to hit `q` and run `:Lf` again for it to go to the current buffer's directory. Any idea what is happening here? My vim's current directory works fine when I run something like `:!pwd` . It is only on Lf that it behaves like this.

And thank you for this awesome extension.

**Comment by ptzz** [comment]
Very odd, never seen that. Perhaps you could try add some logging to `OpenLfIn` to figure out what’s going south?

**Comment by Archie-2021** [comment]
> Very odd, never seen that. Perhaps you could try add some logging to `OpenLfIn` to figure out what’s going south?

How can I do that?

 I also noticed that it tries to open the right file at the first try but it fails for some reason. Lf show a error message in the status bar like this mentioning the filename it is supposed to open.

![image](https://user-images.githubusercontent.com/85870778/236431789-a455fe2f-f36e-44bc-b2e5-87bf4091d750.png)

**Comment by ptzz** [comment]
> How can I do that?

Hack away in lf.vim/plugin/lf.vim.

So init.vim is the file you want it to open? Is it a symlink or something? If you do `:echo expand("%")` before opening the file in lf, does it print as expected?

**Comment by Archie-2021** [comment]
> > How can I do that?
> 
> Hack away in lf.vim/plugin/lf.vim.
> 
> So init.vim is the file you want it to open? Is it a symlink or something? If you do `:echo expand("%")` before opening the file in lf, does it print as expected?

Yes it was the file I was trying to open, I doesn't matter which file it is tho, 9 out of 10 it is not going to open it. It was just a show case. And It is not a symlink. 

`:echo expand("%")` prints the filename (as expected)

**Comment by Archie-2021** [comment]
It seems to changing my keybinding to a command like this fix the issue, altho it is still not clear why it is not changing directory correctly autoamtically:

```
map <A-e> :cd %:p:h<CR>:Lf<CR>
```

**Comment by ptzz** [comment]
Maybe interference with some auto changing directory vim setting? You could try empty .vimrc/init.vim with only lf plugin. For me it works as expected also if pwd != current file directory.

**Comment by ptzz** [comment]
> :echo expand("%") prints the filename (as expected)

It prints full path, right?

**Comment by Archie-2021** [comment]
Yeah I think it was because I had an old line in my init.vim that automatically changing directory on buffer change. I can't remember why I added it but now it looks like it works fine.

```
autocmd BufEnter * silent! cd %:p:h
```

Thank you again for this great plugin, lf and vim work very nicely together, it is best for vim IMO.

**Comment by Archie-2021** [comment]
No it just prints the basename.

**Comment by ptzz** [comment]
Right, it prints relative to pwd. Seems somehow pwd changes when launching lf. I'd add some echo debug statements in lf.vim to understand what's happening. But first disable all settings and plugins in vim config and see if it works.

**Comment by ptzz** [comment]
Great that it works now!
