### ISSUE TITLE
In Windows. When opening (default 'l' and '<right>') a file from the lf window, it doesn't work.

### ISSUE THREAD

**Issue by JohanChane** [ptzz/lf.vim#40]
GVim 90
Windows 22H2

**Comment by ptzz** [comment]
Sorry, haven't tried anything on Windows. PRs welcome though.

**Comment by Alaskra** [comment]
> Sorry, haven't tried anything on Windows. PRs welcome though.

Hello, @ptzz . I have open a PR to fix it.
