### ISSUE TITLE
Error detected while processing function <SNR>92_on_floaterm_close[27] .. LfCallback

### ISSUE THREAD

**Issue by rushyang** [ptzz/lf.vim#41]
Hey ptzz,

Appreciate your work on this plugin. I am trying to set it up and have followed installation steps and installed dependencies of floaterm as well. 

While calling any of the Lf commands, I am getting error - 

```
Error detected while processing function <SNR>92_on_floaterm_close[27]..LfCallback:
line   26:
lf returned non-zero exit code 127
```
I checked scriptnames and 92nd Script is: ```vim-floaterm/autoload/floaterm/terminal.vim```. [Here](https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/terminal.vim#L26)

I just ensured all plugins are at the latest version. 

Is there anything that I am missing? 

Thanks.

**Comment by ptzz** [comment]
127 indicates lf command not found. Where is it installed? Maybe the shell paths are not set up properly in vim.
