### ISSUE TITLE
How to change directory using Lf?

### ISSUE THREAD

**Issue by Archie-2021** [ptzz/lf.vim#42]
I want to combine this plugin with Telescope on a command. For example I want to switch to a directory and do a live grep in it using Telescope. The issue is that right now without this option I have to manually use vim internal `cd` command to do it. I see a Lfcd and Lflcd in commands related to Lf but can't find any documentation about them and not sure how to use it. Is there a way to use Lf to change directory without changing the current buffer?

Sorry for asking this here as I know it is more of a question rather than a bug but there is no discussion tab. 

Thanks

**Comment by ptzz** [comment]
Hi, sorry for the late reply. I haven't used Lfcd myself, seems it arrived in an external PR. Looks like it still opens a file, but in addition sets the vim working directory to the file location.
