### ISSUE TITLE
Files opened with lf.vim not listed in file history

### ISSUE THREAD

**Issue by tricarte** [ptzz/lf.vim#47]
First of all thank you for this plugin. This issue is probably not related to it but I want to know the reason behind.

I'm using fzf.vim and its `History` command a lot. The issue is that this command does not list recent files opened via lf. This also should not be related to fzf.vim because I have the same situation with another plugin called 'Startify'. It must be a VIM behavior that must be set via a config but I don't know what it is, if there is a such a config of course.

Maybe each of these and other similar plugins maintain their own MRU lists and I hope it's not true.

Thanks in advance.

**Comment by ptzz** [comment]
Iirc I installed https://github.com/pbogut/fzf-mru.vim to fix this issue. Something about vim not updating history until after quit.

**Comment by tricarte** [comment]
fzf-mru.vim works as expected. Thanks.
