### ISSUE TITLE
Cannot open file on Windows 10 PowerShell

### ISSUE THREAD

**Issue by garypippi** [ptzz/lf.vim#7]
I am on Windows 10 PowerShell and using Neovim.
lfrc is `cmd open $nvim %f%`

Lf spawned from neovim does not allow me to open file using l or right arrow key, however lf spawned from powershell works fine. Am I missing something ?

**Comment by ptzz** [comment]
That sounds like a bug. Unfortunately I have no Windows machine to test with. PR welcome!

**Comment by garypippi** [comment]
Thank you for a response.
It worked after I added C:\tmp directory.
Apparently Windows users must specify or add /tmp directory since it does not exist there by default unlike Linux.

**Comment by ptzz** [comment]
Hi again, could you help me check if the latest version c0d8878a085870fefc02c72f595536b13c82f461 solves the problem on Windows (i.e. in case there is no c:\tmp directory)? It generates the tempfile using `tempname()` which presumably returns a valid existing temp path on Windows as well.

**Comment by garypippi** [comment]
Hi, the latest version works without c:\tmp on Windows. Thank you !
